dataFiles:
  - https://stars.renci.org/var/answer_coalesce/2026-04-04/txt_files/links.txt
  - https://stars.renci.org/var/answer_coalesce/2026-04-04/txt_files/nodelabels.txt
  - https://stars.renci.org/var/answer_coalesce/2026-04-04/txt_files/backlinks.txt
  - https://stars.renci.org/var/answer_coalesce/2026-04-04/txt_files/nodenames.txt
  - https://stars.renci.org/var/answer_coalesce/2026-04-04/txt_files/prov.txt
  - https://stars.renci.org/var/answer_coalesce/2026-04-04/txt_files/category_count.txt
