version: "3"
services:
  ac:
    container_name: ac
    image: ac
    build:
        context: .
    ports:
      - "6380:6380"
    environment:
      AC_DUCKDB_PATH: /data/answer-coalesce.duckdb
    volumes:
      - ./answer-coalesce.duckdb:/data/answer-coalesce.duckdb:ro
